### ISSUE TITLE
Popup no longer displaying any content

### ISSUE THREAD

**Issue by c0d1ng** [octplane/Shiny-Shaarli#5]
If I enter Chrome Dev Tools, I see this error message:
`Refused to display 'https://MYDOMAIN/?post=chrome-extension%3A%2F%2Fhajdfkmbdmadjmmpkkbbcnllepomekin%2Ffancy-settings%2Findex.html&title=Shiny%20Shaarly&source=shiny_shaarli' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

However if I change the server to `https://demo.shaarli.org` the popup is working again.

**Comment by c0d1ng** [comment]
I'm sorry, I just noticed that I had this line in my nginx config:
`add_header Content-Security-Policy "frame-ancestors 'self'";`

Just removed it and now it's working again!

**Comment by octplane** [comment]
👍  That's a nice FAQ item :)
