### ISSUE TITLE
"Wrong Token" error with Edge Chromium

### ISSUE THREAD

**Issue by hot22shot** [octplane/Shiny-Shaarli#7]
Hi,

I'm getting an error at login "Wrong Token", this issue goes back some time ago as there an issue opened on Shaarli's github  : https://github.com/shaarli/Shaarli/issues/1594

My version of Shaarli is 0.12.1 hosted as a container in a docker environment.
I tried with Edge Chromium version 87.0.664.75 on different computer with the same result.

Regards

**Comment by yfdyh000** [comment]
`"*://*/*",` be necessary, removed in https://github.com/octplane/Shiny-Shaarli/commit/1456b39493bb5c9491731814177ea97ea53f45e9.
